# 前端 Dockerfile
FROM node:20-alpine

WORKDIR /app

# 设置时区为北京时间
ENV TZ=Asia/Shanghai
# 先复制依赖文件，利用缓存
COPY package*.json ./
RUN npm install

# 再复制其他代码
COPY . .
RUN npm run build

EXPOSE 5173

CMD ["npm", "run", "dev"]
