version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: wireguard_backend
    volumes:
      # 挂载宿主机 WireGuard 配置和命令，便于后端操作
      - ./data/wireguard:/etc/wireguard
      # - /usr/bin/wg:/usr/bin/wg
      # - /usr/sbin/iptables:/usr/sbin/iptables
      # 挂载数据库目录，实现数据持久化
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    # 如需直接操作网络，建议加上特权模式
    # privileged: true
    cap_add:
      - NET_ADMIN
      # - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv4.ip_forward: 1
    network_mode: "host"   # ✅ 关键：使用宿主机网络

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: wireguard_frontend
    volumes:
      - ./frontend/src:/app/src
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    network_mode: "host"   # ✅ 关键：使用宿主机网络
